### ISSUE TITLE
require(...) is not a function

### ISSUE THREAD

**Issue by pajinev** [niksy/postcss-em-media-query#2]
i used with postcss (now with https://github.com/C-Lodder/grunt-postcss)
but it give a message 
require(...) is not a function

Use with jit-grunt and load config

module.exports = {

  default: {
    options: {
      map: false,
      processors: [
        require('autoprefixer')({ grid: true }),

          //require('postcss-media-minmax')(),
          require('postcss-em-media-query')(),

          require('postcss-pxtorem')({
              rootValue: 16,
              unitPrecision: 5,
              //propList: ['font', 'font-size', 'line-height', 'letter-spacing', 'padding', 'margin'],
              propList: ['*', '!border*', '!border-left*', '!border-right*', '!border-bottom*', '!border-top*', '!border-radius*'],
              selectorBlackList: [],
              replace: false,
              mediaQuery: false,
              minPixelValue: 0
          }),

          require('cssnano')({
              preset: ['default', {
                  discardComments: true
                  //{
                      //removeAll: true,
                  //},
              }]
          })

      ],

    },
    //src: 'css/style.css',
    //dest: 'css/style.css'
      src: 'css/*.css'
  }

**Comment by niksy** [comment]
Major version was bumped because of PostCSS 8 support, and with that I switched to ES Modules by default. Since module should have named export `postcss`, this also means that default export is now inside `default` export property. This isn’t problem for ESM, but it changes the way you use it for Common JS.

```js
const { default: postcssEmMediaQuery } = require('postcss-em-media-query)
```

Either that or use previous major version. There isn’t any bug fixes or feature changes.

**Comment by niksy** [comment]
@pajinev actually, I was wrong, [official recommendation says otherwise](https://github.com/postcss/postcss/issues/1441), so I pushed new major version with changes. Your code should work now as before.

**Comment by pajinev** [comment]
You are great! THX
